ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.1
    use_sim_time: true
    two_d_mode: true
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
    imu0: /imu
    imu0_config: [false, false, false,
                  true,  true,  true, 
                  false, false, false, 
                  true,  true,  true, 
                  true, true, true] 
    imu0_differential: false
    imu0_relative: true
    imu0_queue_size: 10
    use_control: false
    stamped_control: false
    odom0: /odom_diff
    odom0_config: [true, true, false, # x, y, z
                   false, false, false, # roll, pitch, yaw
                   false, false, false,
                   false, false, true,
                   false, false, false]
    odom0_differential: true

