slam_toolbox:
  ros__parameters:
    mode: 'mapping'
    map_file_name: ''
    resolution: 0.25
    max_laser_range: 50.0
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_topic: '/scan'
    odom_topic: '/odom'
    map_frame: 'map'
    odom_frame: 'odom'
    base_frame: 'base_link'
    link_scan_maximum_distance: 5.0
    do_loop_closing: true
    loop_search_space_dimension: 50.0
    loop_search_maximum_distance: 50.0
    link_match_minimum_response_fine: 0.5
    use_response_expansion: true
    use_scan_matching: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 5.0
    loop_match_minimum_response_fine: 0.1
    loop_match_minimum_response_coarse: 0.2
